import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar"
import Header from "../components/Header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className="h-full bg-gray-50 text-gray-900 antialiased"
      >
        <div className="flex h-screen">
          <Sidebar /> {/* Sidebar on the left*/}

          <div className="flex-1 flex flex-col">
            <Header /> {/* Header at the top */}
            <main className="flex-1 p-6 bg-gray-100">
              {children}
              </main> {/* Page content */}
          </div>
        </div>
      </body>
    </html>
  );
}
