import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar"
import Header from "../components/Header"
import Link from 'next/link';
import { ThemeProvider } from "@/components/ThemeContext";
import DarkModeToggle from "@/components/DarkModeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body>
        <ThemeProvider>
          <nav className="bg=gray-800 text-white p-4 flex gap-4">
            <NavLink href="/" label="Home" />
            <NavLink href="/dashboard" label="Dashboard" />
            <NavLink href="/reports" label="Reports" />
            <NavLink href="/settings" label="Settings" />
            <DarkModeToggle />
          </nav>
          <main className="flex-1 p-6 bg-gray-100">
            {children}
          </main> {/* Page content */}
        </ThemeProvider> 
      </body>
    </html>
  );
}

function NavLink({ href, label }: { href: string, label: string}) {
  const path = typeof window !== 'undefined' ? window.location.pathname : '';
  const isActive = path === href;
  return (
    <Link href={href} className={`hover:underline ${isActive ? 'text-blue-400' : ''}`}>
      {label}
    </Link>
  )
}
